/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AuthorizationConfig } from "./global/interfaces";
import { Propriedades } from "./components/documentos-natureza-pasta-link/documentos-natureza-pasta-link";
export namespace Components {
    interface NopaperAssinatura {
        "situacao": string;
    }
    interface NopaperDetalhesAssinatura {
        "accessToken": string;
        "assinaturaBaseUrl": string;
        "authorization": AuthorizationConfig;
        "invalidProtocoloMessage": string;
        "protocolo": string;
        "refresh": () => Promise<void>;
        "userAccess": string;
        "usuariosBaseUrl": string;
    }
    interface NopaperDocumentosNaturezaPastaLink {
        /**
          * TODO: renan.silvano - documentar
         */
        "propriedades": Propriedades;
    }
}
declare global {
    interface HTMLNopaperAssinaturaElement extends Components.NopaperAssinatura, HTMLStencilElement {
    }
    var HTMLNopaperAssinaturaElement: {
        prototype: HTMLNopaperAssinaturaElement;
        new (): HTMLNopaperAssinaturaElement;
    };
    interface HTMLNopaperDetalhesAssinaturaElement extends Components.NopaperDetalhesAssinatura, HTMLStencilElement {
    }
    var HTMLNopaperDetalhesAssinaturaElement: {
        prototype: HTMLNopaperDetalhesAssinaturaElement;
        new (): HTMLNopaperDetalhesAssinaturaElement;
    };
    interface HTMLNopaperDocumentosNaturezaPastaLinkElement extends Components.NopaperDocumentosNaturezaPastaLink, HTMLStencilElement {
    }
    var HTMLNopaperDocumentosNaturezaPastaLinkElement: {
        prototype: HTMLNopaperDocumentosNaturezaPastaLinkElement;
        new (): HTMLNopaperDocumentosNaturezaPastaLinkElement;
    };
    interface HTMLElementTagNameMap {
        "nopaper-assinatura": HTMLNopaperAssinaturaElement;
        "nopaper-detalhes-assinatura": HTMLNopaperDetalhesAssinaturaElement;
        "nopaper-documentos-natureza-pasta-link": HTMLNopaperDocumentosNaturezaPastaLinkElement;
    }
}
declare namespace LocalJSX {
    interface NopaperAssinatura {
        "situacao"?: string;
    }
    interface NopaperDetalhesAssinatura {
        "accessToken"?: string;
        "assinaturaBaseUrl"?: string;
        "authorization"?: AuthorizationConfig;
        "invalidProtocoloMessage"?: string;
        "protocolo"?: string;
        "userAccess"?: string;
        "usuariosBaseUrl"?: string;
    }
    interface NopaperDocumentosNaturezaPastaLink {
        /**
          * TODO: renan.silvano - documentar
         */
        "propriedades"?: Propriedades;
    }
    interface IntrinsicElements {
        "nopaper-assinatura": NopaperAssinatura;
        "nopaper-detalhes-assinatura": NopaperDetalhesAssinatura;
        "nopaper-documentos-natureza-pasta-link": NopaperDocumentosNaturezaPastaLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nopaper-assinatura": LocalJSX.NopaperAssinatura & JSXBase.HTMLAttributes<HTMLNopaperAssinaturaElement>;
            "nopaper-detalhes-assinatura": LocalJSX.NopaperDetalhesAssinatura & JSXBase.HTMLAttributes<HTMLNopaperDetalhesAssinaturaElement>;
            "nopaper-documentos-natureza-pasta-link": LocalJSX.NopaperDocumentosNaturezaPastaLink & JSXBase.HTMLAttributes<HTMLNopaperDocumentosNaturezaPastaLinkElement>;
        }
    }
}
