/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AuthorizationConfig } from "./global/interfaces";
export namespace Components {
    interface NopaperAssinatura {
        "situacao": string;
    }
    interface NopaperDetalhesAssinatura {
        "accessToken": string;
        "assinaturaBaseUrl": string;
        "authorization": AuthorizationConfig;
        "exibirLinkPara": string;
        "frontAssinadorBaseUrl": string;
        "invalidProtocoloMessage": string;
        "linkAssinador": boolean;
        "protocolo": string;
        "refresh": () => Promise<void>;
        "userAccess": string;
        "usuariosBaseUrl": string;
    }
}
declare global {
    interface HTMLNopaperAssinaturaElement extends Components.NopaperAssinatura, HTMLStencilElement {
    }
    var HTMLNopaperAssinaturaElement: {
        prototype: HTMLNopaperAssinaturaElement;
        new (): HTMLNopaperAssinaturaElement;
    };
    interface HTMLNopaperDetalhesAssinaturaElement extends Components.NopaperDetalhesAssinatura, HTMLStencilElement {
    }
    var HTMLNopaperDetalhesAssinaturaElement: {
        prototype: HTMLNopaperDetalhesAssinaturaElement;
        new (): HTMLNopaperDetalhesAssinaturaElement;
    };
    interface HTMLElementTagNameMap {
        "nopaper-assinatura": HTMLNopaperAssinaturaElement;
        "nopaper-detalhes-assinatura": HTMLNopaperDetalhesAssinaturaElement;
    }
}
declare namespace LocalJSX {
    interface NopaperAssinatura {
        "situacao"?: string;
    }
    interface NopaperDetalhesAssinatura {
        "accessToken"?: string;
        "assinaturaBaseUrl"?: string;
        "authorization"?: AuthorizationConfig;
        "exibirLinkPara"?: string;
        "frontAssinadorBaseUrl"?: string;
        "invalidProtocoloMessage"?: string;
        "linkAssinador"?: boolean;
        "onLinkCopied"?: (event: CustomEvent<string>) => void;
        "protocolo"?: string;
        "userAccess"?: string;
        "usuariosBaseUrl"?: string;
    }
    interface IntrinsicElements {
        "nopaper-assinatura": NopaperAssinatura;
        "nopaper-detalhes-assinatura": NopaperDetalhesAssinatura;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nopaper-assinatura": LocalJSX.NopaperAssinatura & JSXBase.HTMLAttributes<HTMLNopaperAssinaturaElement>;
            "nopaper-detalhes-assinatura": LocalJSX.NopaperDetalhesAssinatura & JSXBase.HTMLAttributes<HTMLNopaperDetalhesAssinaturaElement>;
        }
    }
}
