name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.17'
          registry-url: 'https://registry.npmjs.org'
          scope: '@betha-plataforma'
    
      - name: Install
        run: yarn install --frozen-lockfile
      
      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
      
      - name: Publish
        run: yarn publish --access public --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
