name: Release

on:
  push:
    tags:
      - v*

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@betha-plataforma'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Publish
        run: npm publish --access public