name: Pull Request

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: yarn install --frozen-lockfile

#      - name: Test
#        run: yarn test

      - name: Build
        run: yarn build
